<a href="https://colab.research.google.com/github/Anvesana/PyTorch_Tutorials/blob/main/Intro2DL_June2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

In [2]:
import torch

In [1]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

In [2]:
import torch
import numpy as np

In [3]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.95497191, 0.8601958 , 0.9631787 , 0.03686602],
       [0.36082793, 0.9359106 , 0.00475789, 0.4735145 ],
       [0.74316318, 0.33615629, 0.56489334, 0.08667303]])

In [6]:
np1.dtype

dtype('float64')

# **Tensors**

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.6477,  0.7447,  1.0049,  0.7724],
        [ 1.1179, -0.3734,  0.8091, -0.4082],
        [ 0.7449,  1.2452, -0.0738, -0.1505]])

In [14]:
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
tensor_3d.dtype

torch.float32

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9550, 0.8602, 0.9632, 0.0369],
        [0.3608, 0.9359, 0.0048, 0.4735],
        [0.7432, 0.3362, 0.5649, 0.0867]], dtype=torch.float64)

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch5[1] = 121
my_torch5

tensor([  0, 121,   2,   3,   4,   5,   6,   7,   8,   9])

In [11]:
my_torch6

tensor([[  0, 121,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [12]:
# Slicing
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch7[7]

tensor(7)

In [15]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])